event_gen:
  target: clickhouse
  outputs:
    dev:
      type: clickhouse
      host: clickhouse
      port: 9000
      user: default
      password: ''
      database: events_db
      schema: events_db
      threads: 4
      secure: false
    clickhouse:
      type: clickhouse
      host: clickhouse
      port: 9000
      user: default
      password: ''
      database: events_db
      schema: events_db
      threads: 4
      secure: false