# Dockerfile for Kafka producer
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir \
    psycopg2-binary \
    kafka-python \
    faker

# Run the producer
CMD ["python", "event_producer.py"]